// Code generated by tools/genbound. DO NOT EDIT.
// Regenerate with: go run ./tools/genbound

//go:build darwin

package main

import (
	"encoding/json"

	"dr-markdown/internal/preferences"
)

// dispatchBound calls a bound method with typed arguments decoded from the
// frontend's JSON. `handled` is false when no such method exists, so the
// caller can tell "unknown method" from "method returned nothing".
func dispatchBound(app *App, name string, args []json.RawMessage) (result any, err error, handled bool) {
	switch name {
	case "OpenDocument":
		v, err := app.OpenDocument()
		return v, err, true
	case "SaveDocument":
		var a0 string
		var a1 string
		if err := decodeArgs(args, &a0, &a1); err != nil {
			return nil, err, true
		}
		return nil, app.SaveDocument(a0, a1), true
	case "SaveDocumentAs":
		var a0 string
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		v, err := app.SaveDocumentAs(a0)
		return v, err, true
	case "SyncDocuments":
		var a0 []OpenDocument
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		app.SyncDocuments(a0)
		return nil, nil, true
	case "SetDirty":
		var a0 bool
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		app.SetDirty(a0)
		return nil, nil, true
	case "UpdateContent":
		var a0 string
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		app.UpdateContent(a0)
		return nil, nil, true
	case "ListFontFamilies":
		return app.ListFontFamilies(), nil, true
	case "LoadPreferences":
		v, err := app.LoadPreferences()
		return v, err, true
	case "SavePreferences":
		var a0 preferences.Preferences
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		return nil, app.SavePreferences(a0), true
	case "OpenRecentDocument":
		var a0 string
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		v, err := app.OpenRecentDocument(a0)
		return v, err, true
	case "ImportImage":
		var a0 string
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		v, err := app.ImportImage(a0)
		return v, err, true
	case "ImportDroppedImage":
		var a0 string
		var a1 string
		if err := decodeArgs(args, &a0, &a1); err != nil {
			return nil, err, true
		}
		v, err := app.ImportDroppedImage(a0, a1)
		return v, err, true
	case "LoadImageAsset":
		var a0 string
		var a1 string
		if err := decodeArgs(args, &a0, &a1); err != nil {
			return nil, err, true
		}
		v, err := app.LoadImageAsset(a0, a1)
		return v, err, true
	case "OpenExternalURL":
		var a0 string
		if err := decodeArgs(args, &a0); err != nil {
			return nil, err, true
		}
		return nil, app.OpenExternalURL(a0), true
	case "RecordClientEvent":
		var a0 string
		var a1 map[string]string
		if err := decodeArgs(args, &a0, &a1); err != nil {
			return nil, err, true
		}
		app.RecordClientEvent(a0, a1)
		return nil, nil, true
	case "RevealImageAsset":
		var a0 string
		var a1 string
		if err := decodeArgs(args, &a0, &a1); err != nil {
			return nil, err, true
		}
		return nil, app.RevealImageAsset(a0, a1), true
	case "ResolveUnsavedChanges":
		return app.ResolveUnsavedChanges(), nil, true
	case "FrontendReady":
		return app.FrontendReady(), nil, true
	}
	return nil, nil, false
}
