package main

import (
	"strings"
	"testing"
)

// The regex detector this replaces matched 17 of 18 methods, because
// UpdateContent is written on one line — it reported a method clean by never
// looking at it. The fixture below includes that exact shape, plus the three
// result arities the dispatcher has to tell apart.
func TestParseAppReadsSignaturesIncludingOneLiners(t *testing.T) {
	src := `package main

func (a *App) SaveDocument(path, content string) error {
	defer a.reportPanic("SaveDocument")
	return nil
}

func (a *App) UpdateContent(content string) { defer a.reportPanic("UpdateContent"); }

func (a *App) SyncDocuments(docs []OpenDocument) {
	defer a.reportPanic("SyncDocuments")
}

func (a *App) LoadPreferences() (preferences.Preferences, error) {
	defer a.reportPanic("LoadPreferences")
	return preferences.Preferences{}, nil
}

func (a *App) RecordClientEvent(event string, fields map[string]string) {
	defer a.reportPanic("RecordClientEvent")
}

func (a *App) Risky(x string) error { return nil }

func (a *App) unexported() {}

func (b *Other) NotOurs() {}
`
	got, err := ParseApp(src)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 6 {
		t.Fatalf("expected 6 bound methods, got %d: %+v", len(got), got)
	}

	// Grouped parameters: `path, content string` is two params of one type, and
	// a generator that emitted one would drop an argument silently.
	save := got[0]
	if len(save.Params) != 2 || save.Params[0].Name != "path" ||
		save.Params[1].Name != "content" || save.Params[1].Type != "string" {
		t.Errorf("grouped parameters parsed wrong: %+v", save.Params)
	}

	if !got[1].Guarded {
		t.Error("the one-line method was reported unguarded; the parser did not look inside it")
	}

	// Composite types must survive verbatim or the generated file will not compile.
	if got[2].Params[0].Type != "[]OpenDocument" {
		t.Errorf("slice type mangled: %q", got[2].Params[0].Type)
	}
	if got[4].Params[1].Type != "map[string]string" {
		t.Errorf("map type mangled: %q", got[4].Params[1].Type)
	}

	if !got[3].ReturnsError() || !got[3].ReturnsValue() {
		t.Errorf("(T, error) misread: %+v", got[3])
	}
	if got[1].ReturnsError() || got[1].ReturnsValue() {
		t.Errorf("a method with no results should return neither: %+v", got[1])
	}
	if !got[0].ReturnsError() || got[0].ReturnsValue() {
		t.Errorf("a method returning only error should have no value: %+v", got[0])
	}

	// An unguarded method must be REPORTED, not skipped. Binding a method whose
	// panic reaches nobody is the defect the guard exists to prevent.
	if got[5].Name != "Risky" || got[5].Guarded {
		t.Errorf("an unguarded method must be reported as unguarded: %+v", got[5])
	}
}

// The three result arities produce three different call shapes, and getting one
// wrong is not a compile error in the GENERATOR — it is a compile error in its
// output, discovered later and further away.
func TestEmitDispatchHandlesEveryResultArity(t *testing.T) {
	got := EmitDispatch([]Method{
		{Name: "SetDirty", Params: []Param{{"dirty", "bool"}}},
		{Name: "SaveDocument", Params: []Param{{"path", "string"}, {"content", "string"}},
			Results: []string{"error"}},
		{Name: "ListFontFamilies", Results: []string{"[]string"}},
		{Name: "LoadPreferences", Results: []string{"preferences.Preferences", "error"}},
		{Name: "SavePreferences", Params: []Param{{"prefs", "preferences.Preferences"}},
			Results: []string{"error"}},
	}, Imports{"preferences": "dr-markdown/internal/preferences"})

	for _, want := range []string{
		"// Code generated by tools/genbound. DO NOT EDIT.",
		"//go:build darwin",
		// no results: call it, resolve null
		"\t\tapp.SetDirty(a0)\n\t\treturn nil, nil, true",
		// error only: the error IS the result
		"\t\treturn nil, app.SaveDocument(a0, a1), true",
		// value only: no error to check
		"\t\treturn app.ListFontFamilies(), nil, true",
		// value and error
		"\t\tv, err := app.LoadPreferences()",
		// typed locals, not interface{} — a qualified struct type must survive
		// into the generated file exactly as written or it will not compile
		"\t\tvar a0 bool",
		"\t\tvar a0 preferences.Preferences",
		"decodeArgs(args, &a0)",
		// the qualified type's package must come across or it will not compile
		"\t\"dr-markdown/internal/preferences\"",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated dispatch is missing:\n  %q\ngot:\n%s", want, got)
		}
	}

	// A package named only by a RESULT type must not be imported: the result is
	// received with `:=`, so its type is never written down and the import would
	// be unused — a compile error in the generated file, far from its cause.
	resultOnly := EmitDispatch(
		[]Method{{Name: "ImportImage", Params: []Param{{"documentPath", "string"}},
			Results: []string{"imageassets.ImportedImage", "error"}}},
		Imports{"imageassets": "dr-markdown/internal/assets"})
	if strings.Contains(resultOnly, "dr-markdown/internal/assets") {
		t.Error("imported a package that only appears in a result type; the generated file will not compile")
	}

	// A method taking no arguments must not emit a decode call; decodeArgs with
	// no targets would reject a frontend that sent an empty array.
	if strings.Contains(got, "case \"ListFontFamilies\":\n\t\tif err := decodeArgs") {
		t.Error("emitted an argument decode for a method that takes none")
	}
}
